version: '2'
services:
  thumbroll-server:
    build: .
    ports:
     - "3000:3000"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "postgresdb"
      POSTGRES_DB: "thumbroll"