version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "thumbroll"
  thumbroll-server:
    build: .
    links:
      - postgres
    ports:
      - "3000:3000"
    environment: 
      NODE_ENV: "production"